"""Platform/OS identifier constants shared by the dialog and system modules."""

PLATFORM_WINDOWS = "windows"
PLATFORM_DARWIN = "darwin"
PLATFORM_MAC = "macos"
PLATFORM_LINUX = "linux"
PLATFORM_LINUX_ALMA = "almalinux"
PLATFORM_LINUX_AMAZON = "amzn"
PLATFORM_LINUX_CENTOS = "centos"
PLATFORM_LINUX_DEBIAN = "debian"
PLATFORM_LINUX_ELEMENTARY = "elementary"
PLATFORM_LINUX_FEDORA = "fedora"
PLATFORM_LINUX_MINT = "linuxmint"
PLATFORM_LINUX_POP = "pop"
PLATFORM_LINUX_RHEL = "rhel"
PLATFORM_LINUX_ROCKY = "rocky"
PLATFORM_LINUX_UBUNTU = "ubuntu"
PLATFORM_LINUX_ZORIN = "zorin"
